project:
  type: website
  output-dir: docs

website:
  title: "weekend_experiments"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MosGeo
      - icon: twitter
        href: https://twitter.com/MustafaGeo
format:
  html:
    theme: cosmo
    css: styles.css



